version: '3.3'

networks:
  stayapp:
    driver: bridge

services:
  mockup:
    build: ./mock/
    volumes:
      - ./mock/database.json:/app/database.json
    networks:
      - stayapp
    ports:
      - 8000:8000

  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    networks:
      - stayapp
    ports:
      - 4200:4200
    depends_on:
      - mockup
